# Site Settings
title: "Hyunhoo Bae"
description: "Student at Dougherty Valley High School"
locale: "en-US"

# 가장 안정적인 기본 테마로 임시 변경하여 빌드 성공 확인
theme: minima

# Site Author
author:
  name   : "Hyunhoo Bae"
  bio    : "Competitive Programmer & Student"
  location: "San Ramon, CA"
  picture: "/25PHk.png"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hyunhoo-bae"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
 - "about.md"
 - "academics.md"
# Navigation 설정 추가
#navigation:
#  - title: "About"
#    url: /about/
#  - title: "Projects"
#    url: /projects/
#  - title: "Academics"
#    url: /Academics/
#  - title: "Research"
#    url: /Research/
#  - title: "Volunteer"
#    url: /Volunteer/
