# Site Settings
title: "Hyunhoo Bae"
locale: "en-US"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Minimal Mistakes 관련 필수 설정
minimal_mistakes_skin: "default" # 혹은 "air", "contrast", "mint" 중 선택 가능

# Site Author
author:
  name   : "Hyunhoo Bae"
  bio    : "Student at Dougherty Valley High School"
  location: "San Ramon, CA"
  picture: "/25PHk.png" # 파일명 앞에 슬래시 꼭 확인!
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hyunhoo-bae"

# Build Settings
include: ["_pages", "_posts", "_data"]
exclude: ["Node_modules", "vendor/", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json"]

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
